name: gitea
version: 1.9.2
appVersion: 1.9.2
description: Git with a cup of tea
icon: https://docs.gitea.io/images/gitea.png
keywords:
- git
- issue tracker
- code review
- wiki
- gitea
- gogs
sources:
- https://github.com/go-gitea/gitea
- https://hub.docker.com/r/gitea/gitea/
maintainers:
- name: Josip Radic
  email: josip.radic@gmail.com
