images:
  gitea: "gitea/gitea:1.9.2"
  postgres: "postgres:11.5-alpine"
  memcached: "memcached:1.5.16-alpine"

ingress:
  enabled: true

service:
  http:
    serviceType: ClusterIP
    externalHost: gitea.192.168.1.158.xip.io
    externalPort: 80
    port: 3000
  ssh:
    serviceType: LoadBalancer
    externalHost: git.192.168.1.158.xip.io
    externalPort: 22
    port: 22

persistence:
  enabled: true
  storageClass: hostpath
  accessMode: ReadWriteOnce

config:
  # turn this off in case of redeployment to skip the installation process
  disableInstaller: false
