apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-ssh
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.service.ssh.serviceType }}
  ports:
  - name: ssh
    port: {{ .Values.service.ssh.externalPort }}
    {{- if  .Values.service.ssh.nodePort }}
    nodePort: {{ .Values.service.ssh.nodePort }}
    {{- end }}
    {{- if  .Values.service.ssh.port }}
    targetPort: {{ .Values.service.ssh.port }}
    {{- else }}
    targetPort: {{ .Values.service.ssh.externalPort }}
    {{- end }}
  selector:
    app: {{ template "fullname" . }}
